# Generated by Django 5.2.6 on 2025-09-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
