# Generated by Django 5.2.6 on 2025-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_expires_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('section', 'row', 'number')},
        ),
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='event',
        ),
    ]
