# Generated by Django 5.2.6 on 2025-09-25 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_seat_unique_together_seat_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['section', 'row', 'number']},
        ),
        migrations.AddField(
            model_name='seat',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event', 'seat'], name='booking_boo_event_i_4fa743_idx'),
        ),
    ]
