# Generated by Django 6.0.3 on 2026-03-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_replace_unique_booked_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('held', 'Held'), ('booked', 'Booked'), ('expired', 'Expired')], default='held', max_length=16),
        ),
    ]
