# Generated by Django 6.0.3 on 2026-03-22 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['section', 'row', 'number'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена на момент бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.seat', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('held', 'Удержание'), ('booked', 'Подтверждено'), ('expired', 'Истекло')], default='held', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.PositiveIntegerField(verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='section',
            field=models.CharField(max_length=32, verbose_name='Секция'),
        ),
    ]
