# Generated by Django 6.0.3 on 2026-03-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_ticket_issued',
            field=models.BooleanField(default=False, verbose_name='Билет выписан'),
        ),
    ]
